//action types
export const LOAD_PROJECTS_REQUEST = 'LOAD_PROJECTS_REQUEST'
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS'
export const LOAD_PROJECTS_FAILURE = 'LOAD_PROJECTS_FAILURE'

export const SAVE_PROJECTS_REQUEST = 'SAVE_PROJECTS_REQUEST'
export const SAVE_PROJECTS_SUCCESS = 'SAVE_PROJECTS_SUCCESS'
export const SAVE_PROJECTS_FAILURE = 'SAVE_PROJECTS_FAILURE'

export const DELETE_PROJECTS_REQUEST = 'DELETE_PROJECTS_REQUEST'
export const DELETE_PROJECTS_SUCCESS = 'DELETE_PROJECTS_SUCCESS'
export const DELETE_PROJECTS_FAILURE = 'DELETE_PROJECTS_FAILURE'